### ISSUE TITLE
Not very clean in the docs whether `auth` container is required for `github|google` auth

### ISSUE THREAD

**Issue by laissandrade** [wedeploy/docs#16]
https://github.com/cirocosta/hackaday-wedeploy-feedback/issues/21

**Comment by zenorocha** [comment]
Closing this one since Dashboard and Docs now shows this info:

<img width="638" alt="screen shot 2016-08-29 at 4 53 34 pm" src="https://cloud.githubusercontent.com/assets/398893/18071243/18038186-6e09-11e6-8035-da99f07fd8cf.png">

<img width="552" alt="screen shot 2016-08-29 at 5 01 11 pm" src="https://cloud.githubusercontent.com/assets/398893/18071389/3ea96174-6e0a-11e6-902c-d4b11372890b.png">

http://wedeploy.com/docs/auth/js/
